// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_types from "rescript/lib/es6/js_types.js";

function blockStr(n, x) {
  var x$1 = Js_types.classify(x);
  if (typeof x$1 === "number") {
    return "";
  }
  if (x$1.TAG !== /* JSString */1) {
    return "";
  }
  var x_ = x$1._0.replace(/\s/g, "");
  var pat = new RegExp("\\S{" + n + "}", "g");
  return x_.replace(pat, "$& ");
}

function blockStr3(param) {
  return blockStr("3", param);
}

function blockStr4(param) {
  return blockStr("4", param);
}

function blockStr5(param) {
  return blockStr("5", param);
}

export {
  blockStr ,
  blockStr3 ,
  blockStr4 ,
  blockStr5 ,
  
}
/* No side effect */
